spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  flyway:
    locations:
      - classpath:/db/migration
security:
  encoding-strength: 10

---

spring:
  profiles:
    - production
    - staging
    - develop
  redis:
    host: ${SESSION_STORE_HOST}
    port: ${SESSION_STORE_PORT}
  session:
    store-type: redis

---

spring:
  profiles:
    - develop-standalone
  session:
    store-type: jdbc
  datasource:
    url: jdbc:mysql://localhost:3306/ibex?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: ibex
    password: ibex

---

spring:
  profiles:
    - develop
    - develop-standalone
  flyway:
    locations:
      - classpath:/db/migration
      - classpath:/dev/db/migration
