version: '3.6'

services:
  ibex-database:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ibex
      - MYSQL_USER=ibex
      - MYSQL_PASSWORD=ibex
    restart: always
  ibex-session-store:
    image: redis:4
    restart: always
  ibex-backend:
    depends_on:
      - ibex-database
    links:
      - ibex-database
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=ibex-database
      - DATABASE_PORT=3306
      - DATABASE_NAME=ibex
      - DATABASE_USER=ibex
      - DATABASE_PASSWORD=ibex
      - SESSION_STORE_HOST=ibex-session-store
      - SESSION_STORE_PORT=6379
    restart: always
  ibex-frontend:
    depends_on:
      - ibex-backend
    links:
      - ibex-backend
    ports:
      - "8070:80"
    restart: always
    tmpfs:
      - /usr/share/nginx/html_tmpfs
