version: '3'

services:
  ibex-backend:
    image: registry.ibex.renehollander.at/ibex/backend:production
    environment:
      - spring.profiles.active=production
  ibex-frontend:
    image: registry.ibex.renehollander.at/ibex/frontend:production
