version: '3.6'

services:
  ibex-database:
    volumes:
      - /var/ibex/database:/var/lib/mysql
  ibex-backend:
    image: registry.ibex.renehollander.at/ibex/backend:staging
    environment:
      - spring.profiles.active=staging
  ibex-frontend:
    image: registry.ibex.renehollander.at/ibex/frontend:staging
